{
  "openapi": "3.0.1",
  "info": {
    "title": "Dihann's Tech Shop API",
    "version": "1.0.0",
    "description": "A mock e-commerce api made for user, cart, and order transactions for a tech store."
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Main server"
    }
  ],
  "tags": [
    {
      "name": "Authentication",
      "description": "Authentication to be able to use the cart & checkout"
    },
    {
      "name": "User",
      "description": "Operations about user"
    },
    {
      "name": "Products",
      "description": "Information about Products"
    },
    {
      "name": "Cart",
      "description": "Information about your Carts"
    },
    {
      "name": "Orders",
      "description": "Information about your orders"    
    }
  ],
  "paths": {
    "/api/register": {
      "summary": "Input user data to register.",
      "description": "This path is for creating an account to add items to your cart and make purchases.",
      "post": {
        "summary": "Creates an account for a new user.",
        "description": "Creates an account for a new user.",
        "operationId": "post_register",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "description": "Object for creating new user.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Registration"
              },
              "example": {
                "first_name": "Example",
                "last_name": "User",
                "email": "exampl@email.com",
                "password": "secret_password"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created",
            "content": {
              "text/plain": {
                "example": "User created"
              }
            }
          },
          "400": {
            "description": "Invalid entries in request body",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Email already in use"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "summary": "Login to your account.",
      "description": "This path is for logging in to your account to access account functions.",
      "post": {
        "summary": "Login to your account.",
        "description": "Enter your username(email) and password to login with Passport and access your user info, cart, and orders.",
        "operationId": "post_login",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "description": "Object for logging into account.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "example": {
                "username": "exampl@email.com",
                "password": "secret_password"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User is logged in.",
            "content": {
              "text/plain": {
                "example": "Login successful"
              }
            }
          },
          "400": {
            "description": "Invalid entries in request body.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Email/Password not found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/products": {
      "get": {
        "summary": "Returns all products.",
        "description": "Gets all products from store database and returns them in order of id.",
        "operationId": "get_products",
        "tags": [
          "Products"
        ],
        "responses": {
          "200": {
            "description": "All product objects returned in an array.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "name": "Gigabyte RTX4070",
                    "price": "$1299.00",
                    "category": "Graphics Cards",
                    "description": "12GB of GDDR6X RAM, the RTX 4070 has a 192-bit memory interface running at speeds of 1313 MHz (effectively 21 Gbps). The GPU operates at 1920 MHz with a boost speed of 2475 MHz."
                  },
                  {
                    "id": 2,
                    "name": "Intel Core I7 14900K",
                    "price": "$769.00",
                    "category": "Processors",
                    "description": "Intel Core i7-14700K 3.4 GHz 20-Core LGA 1700 14th Gen Processor, 20 Cores & 28 Threads, 30MB Cache Memory, 5.6GHz MaxTurbo Boost, Intel UHD Graphics"
                  },
                  "..."
                ]
              }
            }
          }
        }
      }
    },
    "/api/products/{productId}": {
      "get": {
        "summary": "Get product object by product id.",
        "description": "Using id parameter, product object is fetched from database.",
        "operationId": "get_product_id",
        "tags": [
          "Products"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "description": "The id of the product.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns product with id matching the id parameter.",
            "content": {
              "application/json": {
                "example": {
                    "id": 1,
                    "name": "Gigabyte RTX4070",
                    "price": "$1299.00",
                    "category": "Graphics Cards",
                    "description": "12GB of GDDR6X RAM, the RTX 4070 has a 192-bit memory interface running at speeds of 1313 MHz (effectively 21 Gbps). The GPU operates at 1920 MHz with a boost speed of 2475 MHz."
                }
              }
            }
          },
          "400": {
            "description": "Error for inavlid product id.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid product number"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/products/categories/{category}": {
      "get": {
        "summary": "Get products in specified category.",
        "description": "fetches all products in a category using the category parameter.",
        "operationId": "get_products_categories",
        "tags": [
          "Products"
        ],
        "parameters": [
          {
            "name": "category",
            "in": "path",
            "description": "category of products",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns all product objects in the selected category, in an array.",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "name": "Gigabyte RTX4070",
                    "price": "$1299.00",
                    "category": "Graphics Cards",
                    "description": "12GB of GDDR6X RAM, the RTX 4070 has a 192-bit memory interface running at speeds of 1313 MHz (effectively 21 Gbps). The GPU operates at 1920 MHz with a boost speed of 2475 MHz."
                  },
                  {
                    "id": 3,
                    "name": "ASUS RTX2070",
                    "price": "$1,139.00",
                    "category": "Graphics Cards",
                    "description": "ASUS Dual GeForce RTXâ„¢ 2070 EVO 8GB GDDR6 with high-performance cooling for 4K and high refresh rate gaming."
                  },
                  "..."
                ]
              }
            }
          },
          "400": {
            "description": "Error for inavlid product category.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid category"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/user": {
      "summary": "Access user account.",
      "description": "Path for accessing and updating user account information.",
      "get": {
        "summary": "Get user account information.",
        "description": "Fetches user account information if logged in with Passport. Password not shown with info.",
        "operationId": "get_user",
        "tags": [
          "User"
        ],
        "responses": {
          "200": {
            "description": "Object containing user info.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": 34,
                  "first_name": "Example",
                  "last_name": "user",
                  "email": "exampl@email.com",
                  "password": "********",
                  "created": "2022-03-10T20:52:21.278Z",
                  "modified": null
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update account information.",
        "description": "Update account information if logged in with Passport.",
        "operationId": "put_user",
        "tags": [
          "User"
        ],
        "requestBody": {
          "description": "Update user data by sending data you want changed in key value pairs.\nYou can send one or many updates in the same request body.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Registration"
              },
              "examples": {
                "name change": {
                  "value": {
                    "first_name": "New",
                    "last_name": "Name"
                  }
                },
                "email change": {
                  "value": {
                    "email": "newemail@gmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update response",
            "content": {
              "text/plain": {
                "example": "Update successful"
              }
            }
          },
          "400": {
            "description": "Information entered does not fit schema.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid entries"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes user account",
        "description": "Deletes your account from the database. Make sure you want to delete because there is no recovery proccess.",
        "operationId": "delete_user",
        "tags": [
          "User"
        ],
        "responses": {
          "204": {
            "description": "No content - Delete successful"
          }
        }
      }
    },
    "/api/carts": {
      "description": "Access users carts",
      "get": {
        "summary": "Get user cart information.",
        "description": "Fetches user cart information. Fetches multiple carts if user has multiple carts. Uses user id from passport Login.",
        "operationId": "get_carts",
        "tags": [
          "Cart"
        ],
        "responses": {
          "200": {
            "description": "Returns array of user's cart objects",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Carts"
                },
                "example": [
                  {
                    "id": 7,
                    "user_id": 67,
                    "created": "2022-03-10T21:02:57.840Z",
                    "modified": null
                  },
                  {
                    "id": 6,
                    "user_id": 67,
                    "created": "2022-03-10T21:02:01.460Z",
                    "modified": "2022-03-10T21:08:23.713Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "No carts under your user id",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "No carts found"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creates a new cart.",
        "description": "Creates a new cart using the user id provided by your Passport login.",
        "operationId": "post_carts",
        "tags": [
          "Cart"
        ],
        "responses": {
          "201": {
            "description": "Cart created",
            "content": {
              "text/plain": {
                "example": "Cart created"
              }
            }
          }
        }
      }
    },
    "/api/carts/{cartId}": {
      "description": "Preform CRUD operations on a cart based on cart id from parameters and user id provided by your Passport login.",
      "get": {
        "summary": "Get cart by cart id.",
        "description": "Fetches user cart information based on cart id and the user id provided by your Passport login.",
        "operationId": "get_carts_id",
        "tags": [
          "Cart"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns cart object matching cart id provided.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                },
                "example": {
                  "id": 7,
                  "user_id": 67,
                  "created": "2022-03-10T21:02:57.840Z",
                  "modified": null
                }
              }
            }
          },
          "400": {
            "description": "Invalid cart id.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid cart id"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete cart by cart id.",
        "description": "Delete cart based on cart id from the parameters and user id provided by your Passport login.",
        "operationId": "delete_carts_id",
        "tags": [
          "Cart"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content - cart deleted"
          }
        }
      }
    },
    "/api/carts/{cartId}/checkout": {
      "get": {
        "summary": "Submit cart for checkout",
        "description": "Creates a new order using all products in the selected cart (parameters) and the user id provided by your Passport login.",
        "operationId": "get_carts_checkout",
        "tags": [
          "Cart/Checkout"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns id of the new order that was created.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Checkout"
                },
                "example": {
                  "order_id": 54
                }
              }
            }
          },
          "400": {
            "description": "No items in cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Cart empty. No order created"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/carts/{cartId}/items": {
      "get": {
        "summary": "Gets all items in cart",
        "description": "Fetches all items in the selected cart (cart id from parameter and user id provided by your Passport login).",
        "operationId": "get_cart_items",
        "tags": [
          "Cart/Items"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "All product objects in cart returned in an array.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductAllCart"
                },
                "example": [
                  {
                    "id": 1,
                    "name": "Gigabyte RTX4070",
                    "price": "$1299.00",
                    "category": "Graphics Cards",
                    "description": "12GB of GDDR6X RAM, the RTX 4070 has a 192-bit memory interface running at speeds of 1313 MHz (effectively 21 Gbps). The GPU operates at 1920 MHz with a boost speed of 2475 MHz.",
                    "qty": 1                  
                  },
                  {
                    "id": 3,
                    "name": "ASUS RTX2070",
                    "price": "$1,139.00",
                    "category": "Graphics Cards",
                    "description": "ASUS Dual GeForce RTXâ„¢ 2070 EVO 8GB GDDR6 with high-performance cooling for 4K and high refresh rate gaming.",
                    "qty": 1                  
                  },
                  "..."
                ]
              }
            }
          },
          "400": {
            "description": "No items in cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Cart Empty"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Add item to cart",
        "description": "Add item to the selected cart (cart id from parameter and user id provided by your Passport login).",
        "operationId": "post_cart_items",
        "tags": [
          "Cart/Items"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Submit product id and qty in request body.",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductAdd"
              },
              "example": {
                "product_id": 30,
                "qty": 5
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Item added to cart",
            "content": {
              "text/plain": {
                "example": "Product added"
              }
            }
          },
          "400": {
            "description": "Invalid product id",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Invalid product Id"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/carts/{cartId}/items/{itemId}": {
      "get": {
        "summary": "Get item in cart by item id",
        "description": "Fetch item from the selected cart (cart id from parameter and user id provided by your Passport login) by item id.",
        "operationId": "get_cart_item_id",
        "tags": [
          "Cart/Items"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "itemId",
            "in": "path",
            "description": "Product id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns product object that matched input",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductSingleCart"
                },
                "example": {
                  "id": 3,
                  "name": "ASUS RTX2070",
                  "price": "$1,139.00",
                  "category": "Graphics Cards",
                  "description": "ASUS Dual GeForce RTXâ„¢ 2070 EVO 8GB GDDR6 with high-performance cooling for 4K and high refresh rate gaming.",
                  "qty": 1
                }
              }
            }
          },
          "400": {
            "description": "Product with selected id not in cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Product not found"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update item quantity in cart",
        "description": "Update item quantity in selected cart (cart id from parameter and user id provided by your Passport login.) by item id.",
        "operationId": "put_cart_item_id",
        "tags": [
          "Cart/Items"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "itemId",
            "in": "path",
            "description": "Product id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Submit updated qty in request body.",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateQty"
              },
              "example": {
                "qty": 5
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Quantity updated successfully",
            "content": {
              "text/plain": {
                "example": "Qty updated"
              }
            }
          },
          "400": {
            "description": "Product with selected id not in cart",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Product not found"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Removes item from cart",
        "description": "Removes item from selected cart (cart id from parameter and user id provided by your Passport login) by item id.",
        "operationId": "delete_cart_item_id",
        "tags": [
          "Cart/Items"
        ],
        "parameters": [
          {
            "name": "cartId",
            "in": "path",
            "description": "Cart id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "itemId",
            "in": "path",
            "description": "Product id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content - Delete successful"
          }
        }
      }
    },
    "/api/orders": {
      "get": {
        "summary": "Get all orders.",
        "description": "Fetches all orders for your account. User id for fetching accounts is provided by your Passport login.",
        "operationId": "get_orders",
        "tags": [
          "Orders"
        ],
        "responses": {
          "200": {
            "description": "All order objects sent in an array.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OrdersAll"
                },
                "example": [
                  {
                    "id": 12,
                    "user_id": 67,
                    "total_price": "$41.00",
                    "status": "SHIPPED",
                    "created": "2022-03-10T21:16:54.502Z",
                    "modified": "2022-03-10T21:16:54.515Z"
                  },
                  {
                    "id": 13,
                    "user_id": 67,
                    "total_price": "$100.00",
                    "status": "PENDING",
                    "created": "2022-03-10T21:19:56.294Z",
                    "modified": "2022-03-10T21:20:43.543Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "No orders found.",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "No orders found"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/orders/{orderId}": {
      "get": {
        "summary": "Get order by order id.",
        "description": "Fetches an order from your account (user id provided by your Passport login) that matches the order id provided (parameters).\nProducts in order are attached in an array to the order object.",
        "operationId": "get_orders_id",
        "tags": [
          "Orders"
        ],
        "parameters": [
          {
            "name": "orderId",
            "in": "path",
            "description": "Order id.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns order object with id matching the parameters. Products in order are attatched in array.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Order"
                },
                "example": {
                  "id": 13,
                  "user_id": 67,
                  "total_price": "$100.00",
                  "status": "PENDING",
                  "created": "2022-03-10T21:19:56.294Z",
                  "modified": "2022-03-10T21:20:43.543Z",
                  "products": [
                    {
                      "id": 3,
                      "name": "ASUS RTX2070",
                      "price": "$1,139.00",
                      "category": "Graphics Cards",
                      "description": "ASUS Dual GeForce RTXâ„¢ 2070 EVO 8GB GDDR6 with high-performance cooling for 4K and high refresh rate gaming.",
                      "qty": 1
                    },
                    "..."
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Order with that id not found",
            "content": {
              "text/plain": {
                "examples": {
                  "Error": {
                    "value": "Order not found"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Registration": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Login": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "created": {
            "type": "date-time"
          },
          "modified": {
            "type": "date-time"
          }
        }
      },
      "Carts": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "user_id": {
              "type": "integer"
            },
            "created": {
              "type": "date-time"
            },
            "modified": {
              "type": "date-time"
            }
          }
        }
      },
      "Cart": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "user_id": {
            "type": "integer"
          },
          "created": {
            "type": "date-time"
          },
          "modified": {
            "type": "date-time"
          }
        }
      },
      "Checkout": {
        "type": "object",
        "properties": {
          "order_id": {
            "type": "integer"
          }
        }
      },
      "ProductAllCart": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "price": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "qty": {
              "type": "integer"
            }
          }
        }
      },
      "ProductAdd": {
        "type": "object",
        "properties": {
          "product_id": {
            "type": "integer"
          },
          "qty": {
            "type": "integer"
          }
        }
      },
      "ProductSingleCart": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "qty": {
            "type": "integer"
          }
        }
      },
      "UpdateQty": {
        "type": "object",
        "properties": {
          "qty": {
            "type": "integer"
          }
        }
      },
      "OrdersAll": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "user_id": {
              "type": "integer"
            },
            "total_price": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "created": {
              "type": "date-time"
            },
            "modified": {
              "type": "date-time"
            }
          }
        }
      },
      "Order": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "user_id": {
            "type": "integer"
          },
          "total_price": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "created": {
            "type": "date-time"
          },
          "modified": {
            "type": "date-time"
          },
          "products": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "price": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "qty": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    }
  }
}